trigger:
  branches:
    include:
    - refs/heads/main

jobs:
- job: Job_1
  displayName: Agent job 1
  pool:
    vmImage: windows-2019
    
  steps:
  - checkout: self
    fetchDepth: 1

  - task: NuGetCommand@2
    displayName: NuGet pack
    inputs:
      command: pack
      searchPatternPack: MyPackage.nuspec
      versioningScheme: byPrereleaseNumber

  - task: NuGetCommand@2
    displayName: NuGet push
    inputs:
      command: push
      publishVstsFeed: 'buildID/feedID'# we need to add this ID like buildID/feedID
      allowPackageConflicts: true
