trigger:
  paths:
    include:
    - Source/Genie/Infrastructure/infragenie-core

jobs:
- job: Job_1
  displayName: Create a Infra NuGet Package
  pool:
    vmImage: windows-latest
  steps:
  - checkout: self
    fetchDepth: 1
  - task: NuGetToolInstaller@1
    displayName: 'Use NuGet '
  - task: PowerShell@2
    displayName: PowerShell Script
    inputs:
      targetType: inline
      script: Write-Host $(Build.BuildNumber)
  
  - task: BicepBuild@0
    inputs:
      process: 'single'
      sourceFile: 'Source/Genie/Marketplace/marketplace.bicep'
      outputProcess: 'outDir'
      outputDirectory: '$(Build.artifactstagingdirectory)'
    
  - task: BicepBuild@0
    inputs:
      process: 'single'
      sourceFile: 'Source/Genie/Infrastructure/infragenie-core/main.bicep'
      outputProcess: 'outDir'
      outputDirectory: '$(Build.artifactstagingdirectory)'
  
  - task: CopyFiles@2
    displayName: 'Copy Files to:'
    inputs:
      SourceFolder: Source/Genie/Marketplace
      Contents: createUiDefinition.json
      TargetFolder: $(Build.artifactstagingdirectory)

  - task: NuGetCommand@2
    inputs:
      command: 'pack'
      packagesToPack: './Source/Packager/Infra.nuspec'
      versioningScheme: 'byPrereleaseNumber'
      majorVersion: '1'
      minorVersion: '0'
      patchVersion: '0'
  - task: NuGetCommand@2
    inputs:
      command: 'push'
      packagesToPush: '$(Build.ArtifactStagingDirectory)/**/*.nupkg;!$(Build.ArtifactStagingDirectory)/**/*.symbols.nupkg'
      nuGetFeedType: 'internal'
      publishVstsFeed: '100af0af-d05b-42ea-a288-d74c49065583'

  - task: PublishBuildArtifacts@1
    inputs:
      PathtoPublish: '$(Build.artifactstagingdirectory)'
      ArtifactName: 'drop'
      publishLocation: 'Container'

  - task: DownloadPackage@1
    displayName: Download Package 637a1723-5f60-4961-8e40-bc8cc5f9478e
    enabled: False
    inputs:
      feed: efafcb65-a45c-4d5c-a58f-35ec3de2ebb5/a9ac7ec2-1d02-4d9a-988c-64717aee018d
      definition: 637a1723-5f60-4961-8e40-bc8cc5f9478e
      version: 1.0.0-ci-20230705-091125

  - task: DownloadPipelineArtifact@2
    displayName: Download Pipeline Artifact
    inputs:
      source: specific
      project: efafcb65-a45c-4d5c-a58f-35ec3de2ebb5
      pipeline: 20
      path: $(Build.artifactstagingdirectory)

  - task: PowerShell@2
    displayName: 'PowerShell Script '
    inputs:
      targetType: inline
      script: >-
        # Write your PowerShell commands here.


        Write-Host "$(Build.artifactstagingdirectory)\drop"


        Expand-Archive -Path "$(Build.artifactstagingdirectory)\drop\*.nupkg" -DestinationPath "$(Build.artifactstagingdirectory)\drop"
      failOnStderr: true
      pwsh: true

  - task: PublishBuildArtifacts@1
    displayName: 'Publish Artifact: drop '
    inputs:
      PathtoPublish: $(Build.artifactstagingdirectory)\drop\Infra

...




  