CREATE TABLE [dbo].[ChatMessage]
(
	[Id] UNIQUEIDENTIFIER NOT NULL PRIMARY KEY,
	[ThreadId] UNIQUEIDENTIFIER NOT NULL,
	[GroupId] UNIQUEIDENTIFIER  NOT NULL,
	[Request] NVARCHAR(MAX) NOT NULL,
	[Response] NVARCHAR(MAX) NOT NULL,
	[Attempt] INT NOT NULL
)
